// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getSupabase, isSupabaseConfigured } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    if (!isSupabaseConfigured()) {
      return next({ headers: {} })
    }
    try {
      const { data } = await getSupabase().auth.getSession()
      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch (err) {
      console.error('[v0] attachSupabaseAuth error:', err)
      return next({ headers: {} })
    }
  },
)
